//! Compile checks for the Rust scaffold templates.
//!
//! `emergent scaffold` shipped a Rust handler that did not compile for a long
//! time because nothing ever built the generated code. These tests render the
//! templates through the same functions the scaffold pipeline uses, and the
//! `renders_and_compiles` test builds the result against the SDK in this
//! working tree.
//!
//! `renders_and_compiles` is `#[ignore]`d: it invokes cargo, so it takes
//! minutes on a cold cache and needs the crates.io index. Run it explicitly:
//!
//! ```bash
//! cargo test -p emergent-engine --test rust_scaffold_compiles -- --ignored
//! # or
//! cargo nextest run -p emergent-engine --run-ignored all -E 'test(renders_and_compiles)'
//! ```

use std::fs;
use std::path::{Path, PathBuf};
use std::process::Command;

use emergent_engine::scaffold::cli::build_template_context;
use emergent_engine::scaffold::messages::{
    Language, PrimitiveType, ScaffoldRequest, TemplateContext,
};
use emergent_engine::scaffold::templates::render_primitive_files;

/// Every Rust primitive type the scaffold can generate.
const RUST_PRIMITIVES: [PrimitiveType; 3] = [
    PrimitiveType::Source,
    PrimitiveType::Handler,
    PrimitiveType::Sink,
];

/// Builds the scaffold context for one primitive type, as the CLI would.
fn context_for(primitive_type: PrimitiveType) -> TemplateContext {
    let request = ScaffoldRequest {
        language: Language::Rust,
        name: format!("scaffold_{primitive_type}"),
        primitive_type,
        subscribes: vec!["timer.tick".to_string(), "timer.tock".to_string()],
        publishes: vec!["timer.processed".to_string()],
        description: "Generated by the scaffold template compile test".to_string(),
        output_dir: PathBuf::from("."),
        dry_run: false,
        json_output: false,
    };

    build_template_context(&request)
}

/// Renders one primitive, failing the test with the template error on error.
fn render(primitive_type: PrimitiveType) -> Vec<(&'static str, String)> {
    let ctx = context_for(primitive_type);
    match render_primitive_files(Language::Rust, primitive_type, &ctx) {
        Ok(files) => files,
        Err(e) => panic!("rendering the Rust {primitive_type} templates failed: {e}"),
    }
}

/// Writes a file and every missing parent directory.
fn write_file(path: &Path, body: &str) {
    if let Some(parent) = path.parent()
        && let Err(e) = fs::create_dir_all(parent)
    {
        panic!("could not create {}: {e}", parent.display());
    }
    if let Err(e) = fs::write(path, body) {
        panic!("could not write {}: {e}", path.display());
    }
}

/// Repoints the generated `emergent-client` dependency at this working tree.
///
/// The template pins a published version. The point of this test is the SDK
/// next to it, not the one on crates.io, so the pin is swapped for a path
/// dependency. `[workspace]` detaches the generated crate from any workspace
/// that happens to contain the temporary directory.
fn retarget_manifest(manifest: &str, sdk_path: &Path) -> String {
    let mut out = String::new();
    let mut replaced = false;

    for line in manifest.lines() {
        if line.trim_start().starts_with("emergent-client") {
            out.push_str(&format!(
                "emergent-client = {{ path = {:?} }}\n",
                sdk_path.display().to_string()
            ));
            replaced = true;
        } else {
            out.push_str(line);
            out.push('\n');
        }
    }

    assert!(
        replaced,
        "the generated Cargo.toml no longer declares emergent-client, so this \
         test would check the wrong SDK"
    );

    out.push_str("\n[workspace]\n");
    out
}

/// Absolute path to the Rust SDK in this working tree.
fn sdk_path() -> PathBuf {
    let relative = Path::new(env!("CARGO_MANIFEST_DIR")).join("../sdks/rust");
    match fs::canonicalize(&relative) {
        Ok(path) => path,
        Err(e) => panic!("could not resolve the SDK at {}: {e}", relative.display()),
    }
}

#[test]
fn every_rust_primitive_renders() {
    for primitive_type in RUST_PRIMITIVES {
        let files = render(primitive_type);
        let names: Vec<&str> = files.iter().map(|(name, _)| *name).collect();
        assert_eq!(
            names,
            vec!["Cargo.toml", "src/main.rs"],
            "unexpected file set for {primitive_type}"
        );

        for (name, body) in &files {
            assert!(
                !body.trim().is_empty(),
                "{primitive_type} rendered an empty {name}"
            );
            assert!(
                !body.contains("{{"),
                "{primitive_type} left an unrendered placeholder in {name}"
            );
        }
    }
}

#[test]
fn handler_template_publishes_through_its_handler() {
    let files = render(PrimitiveType::Handler);
    let main_rs = files
        .iter()
        .find(|(name, _)| *name == "src/main.rs")
        .map(|(_, body)| body.clone());

    let Some(main_rs) = main_rs else {
        panic!("the handler scaffold no longer renders src/main.rs");
    };

    // This is the shape issue #41 was about. If the template stops publishing
    // through the closure's handler argument, the compile test below stops
    // covering the bug it was written for.
    assert!(
        main_rs.contains("|msg, handler| async move {"),
        "the handler template no longer uses the documented closure shape"
    );
    assert!(
        main_rs.contains("handler.publish(output)"),
        "the handler template no longer publishes through its handler argument"
    );
}

#[test]
#[ignore = "runs cargo check on generated crates; slow and needs the crates.io index"]
fn renders_and_compiles() {
    let sdk = sdk_path();
    let root = match tempfile::TempDir::new() {
        Ok(dir) => dir,
        Err(e) => panic!("could not create a temporary directory: {e}"),
    };
    // One target directory for all three crates, so the shared dependencies
    // are built once.
    let target_dir = root.path().join("target");

    for primitive_type in RUST_PRIMITIVES {
        let crate_dir = root.path().join(primitive_type.as_str());

        for (name, body) in render(primitive_type) {
            let body = if name == "Cargo.toml" {
                retarget_manifest(&body, &sdk)
            } else {
                body
            };
            write_file(&crate_dir.join(name), &body);
        }

        let output = Command::new(env!("CARGO"))
            .arg("check")
            .arg("--quiet")
            .arg("--all-targets")
            .current_dir(&crate_dir)
            .env("CARGO_TARGET_DIR", &target_dir)
            .env_remove("RUSTFLAGS")
            .output();

        let output = match output {
            Ok(output) => output,
            Err(e) => panic!("could not run cargo check for {primitive_type}: {e}"),
        };

        assert!(
            output.status.success(),
            "the generated Rust {primitive_type} does not compile:\n{}",
            String::from_utf8_lossy(&output.stderr)
        );
    }
}
