//! The SDK requirement the scaffold templates render must name a version the
//! SDK in this tree actually is.
//!
//! `emergent scaffold -l rust` shipped `emergent-client = "0.3"` while the SDK
//! was at 0.13, so every generated crate failed to resolve. These tests render
//! the manifests the scaffold writes and check each requirement against the
//! version of the matching SDK.

use std::fs;
use std::path::{Path, PathBuf};

use emergent_client::VERSION as RUST_SDK_VERSION;
use emergent_engine::scaffold::cli::build_template_context;
use emergent_engine::scaffold::messages::{Language, PrimitiveType, ScaffoldRequest};
use emergent_engine::scaffold::templates::render_primitive_files;
use semver::{Version, VersionReq};

/// Every primitive type the scaffold can generate.
const PRIMITIVES: [PrimitiveType; 3] = [
    PrimitiveType::Source,
    PrimitiveType::Handler,
    PrimitiveType::Sink,
];

/// Renders one primitive's files as the scaffold pipeline would.
fn render(language: Language, primitive_type: PrimitiveType) -> Vec<(&'static str, String)> {
    let request = ScaffoldRequest {
        language,
        name: format!("scaffold_{primitive_type}"),
        primitive_type,
        subscribes: vec!["timer.tick".to_string()],
        publishes: vec!["timer.processed".to_string()],
        description: "Generated by the scaffold SDK version test".to_string(),
        output_dir: PathBuf::from("."),
        dry_run: false,
        json_output: false,
    };

    let ctx = build_template_context(&request);
    match render_primitive_files(language, primitive_type, &ctx) {
        Ok(files) => files,
        Err(e) => panic!("rendering the {language} {primitive_type} templates failed: {e}"),
    }
}

/// Returns the body of one rendered file, failing the test if it is missing.
fn file(files: &[(&'static str, String)], name: &str) -> String {
    match files.iter().find(|(file, _)| *file == name) {
        Some((_, body)) => body.clone(),
        None => panic!("the scaffold no longer renders {name}"),
    }
}

/// Absolute path to one directory of this repository.
fn repo_path(relative: &str) -> PathBuf {
    let path = Path::new(env!("CARGO_MANIFEST_DIR"))
        .join("..")
        .join(relative);
    match fs::canonicalize(&path) {
        Ok(path) => path,
        Err(e) => panic!("could not resolve {}: {e}", path.display()),
    }
}

/// Reads a file of this repository.
fn read_repo_file(relative: &str) -> String {
    let path = repo_path(relative);
    match fs::read_to_string(&path) {
        Ok(body) => body,
        Err(e) => panic!("could not read {}: {e}", path.display()),
    }
}

/// The `version` field of a TOML document.
fn toml_version(body: &str, table: &str) -> String {
    let doc: toml::Value = match toml::from_str(body) {
        Ok(doc) => doc,
        Err(e) => panic!("could not parse the {table} manifest: {e}"),
    };

    match doc.get(table).and_then(|t| t.get("version")) {
        Some(toml::Value::String(version)) => version.clone(),
        other => panic!("the {table} manifest has no version string: {other:?}"),
    }
}

#[test]
fn the_rust_manifest_requires_the_sdk_in_this_tree() {
    let sdk = match Version::parse(RUST_SDK_VERSION) {
        Ok(version) => version,
        Err(e) => panic!("the SDK version {RUST_SDK_VERSION} is not semver: {e}"),
    };

    for primitive_type in PRIMITIVES {
        let manifest = file(&render(Language::Rust, primitive_type), "Cargo.toml");
        let doc: toml::Value = match toml::from_str(&manifest) {
            Ok(doc) => doc,
            Err(e) => panic!("the generated {primitive_type} Cargo.toml is not TOML: {e}"),
        };

        let requirement = match doc
            .get("dependencies")
            .and_then(|deps| deps.get("emergent-client"))
        {
            Some(toml::Value::String(requirement)) => requirement.clone(),
            other => panic!(
                "the generated {primitive_type} Cargo.toml does not require emergent-client: {other:?}"
            ),
        };

        let parsed = match VersionReq::parse(&requirement) {
            Ok(parsed) => parsed,
            Err(e) => panic!(
                "the generated {primitive_type} requires \"{requirement}\", which is not a Cargo requirement: {e}"
            ),
        };

        assert!(
            parsed.matches(&sdk),
            "the generated {primitive_type} requires emergent-client \"{requirement}\", \
             which does not accept the SDK in this tree ({RUST_SDK_VERSION})"
        );
    }
}

#[test]
fn the_python_manifest_requires_the_python_sdk_in_this_tree() {
    let version = toml_version(&read_repo_file("sdks/py/pyproject.toml"), "project");
    let expected = format!("emergent-client~={version}");

    for primitive_type in PRIMITIVES {
        let manifest = file(&render(Language::Python, primitive_type), "pyproject.toml");
        assert!(
            manifest.contains(&expected),
            "the generated Python {primitive_type} does not require \"{expected}\":\n{manifest}"
        );
    }
}

#[test]
fn the_typescript_manifest_requires_the_typescript_sdk_in_this_tree() {
    let deno: serde_json::Value = match serde_json::from_str(&read_repo_file("sdks/ts/deno.json")) {
        Ok(deno) => deno,
        Err(e) => panic!("could not parse the TypeScript SDK manifest: {e}"),
    };
    let version = match deno.get("version") {
        Some(serde_json::Value::String(version)) => version.clone(),
        other => panic!("the TypeScript SDK manifest has no version string: {other:?}"),
    };
    let expected = format!("jsr:@govcraft/emergent@^{version}");

    for primitive_type in PRIMITIVES {
        let manifest = file(&render(Language::TypeScript, primitive_type), "deno.json");
        let doc: serde_json::Value = match serde_json::from_str(&manifest) {
            Ok(doc) => doc,
            Err(e) => panic!("the generated {primitive_type} deno.json is not JSON: {e}"),
        };

        let import = doc
            .get("imports")
            .and_then(|imports| imports.get("@govcraft/emergent"))
            .and_then(serde_json::Value::as_str)
            .map(str::to_string);

        assert_eq!(
            import.as_deref(),
            Some(expected.as_str()),
            "the generated TypeScript {primitive_type} imports the wrong SDK specifier"
        );
    }
}

#[test]
fn the_three_sdks_ship_the_same_version() {
    // The scaffold renders every language's requirement from the Rust SDK
    // version, which only stays honest while the SDKs are released together.
    let python = toml_version(&read_repo_file("sdks/py/pyproject.toml"), "project");
    let typescript: serde_json::Value =
        match serde_json::from_str(&read_repo_file("sdks/ts/deno.json")) {
            Ok(doc) => doc,
            Err(e) => panic!("could not parse the TypeScript SDK manifest: {e}"),
        };
    let typescript = typescript
        .get("version")
        .and_then(serde_json::Value::as_str)
        .map(str::to_string);

    assert_eq!(
        python, RUST_SDK_VERSION,
        "the Python SDK is at {python} while the Rust SDK is at {RUST_SDK_VERSION}"
    );
    assert_eq!(
        typescript.as_deref(),
        Some(RUST_SDK_VERSION),
        "the TypeScript SDK and the Rust SDK are at different versions"
    );
}
